Add support to use SELECT query variables in sh:message
RDFLib/pySHACL pull request #50
Opened 2020-05-29 13:02 UTC by piyush69

Add support for #30

2020-05-30 12:02 UTC, piyush69 commented
The commit history is a little messy. Once reviewed and approved, I'll put in a new PR to maintain a clean commit history.

2020-06-07 22:37 UTC, ashleysommer commented
Hi @piyush69 
I commented about this feature in the issue thread here: https://github.com/RDFLib/pySHACL/issues/30#issuecomment-637853613
Did you see that comment?

2020-06-08 03:19 UTC, piyush69 commented
Just saw your comment. I'll get on it right away.

2021-05-26 02:07 UTC, ashleysommer commented
Sorry for the very long delay. I thought I'd already merged this PR. I've pushed some updates to bring it back in line with the current codebase, just waiting for the tests to run.

2021-05-26 03:21 UTC, ashleysommer requested changes
Add another blank line after the new method, to keep the linter happy

2021-05-26 03:21 UTC, ashleysommer commented on pyshacl/constraints/constraint_component.py
> +        return msg
```suggestion
        return msg

```

2021-05-26 03:55 UTC, ashleysommer requested changes
Fix black formatting in sparql_based_constraints.py

2021-05-26 03:55 UTC, ashleysommer commented on pyshacl/constraints/sparql/sparql_based_constraints.py
> +                        bound_vars=(t, p, v), **rept_kwargs)
```suggestion
                    rept = self.make_v_result(
                        target_graph, t or f, value_node=v, result_path=p, bound_vars=(t, p, v), **rept_kwargs
                    )
```

2021-05-26 04:09 UTC, merged